---
- name: Configure xmonad
  copy:
    src: "xmonad/"
    dest: "{{ home_dir }}/.xmonad"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure redshift
  copy:
    src: "config/redshift.conf.j2"
    dest: "{{ home_dir }}/.config/redshift.conf"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Ensure lightdm conf.d exists
  become: True
  file:
    path: "/etc/lightdm/lightdm.conf.d"
    owner: root
    group: root
    state: directory

- name: "Enable autologin for '{{ x_username }}'"
  become: True
  copy:
    src: "12-autologin.conf.j2"
    dest: "/etc/lightdm/lightdm.conf.d/12-autologin.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure X session
  copy:
    src: "xsession.j2"
    dest: "{{ home_dir }}/.xsession"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    mode: 0700
