---
- name: Ensure necessary config directories exist
  file:
    path: "{{ home_dir }}/{{ item }}"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    state: directory
  with_items:
    - '.config'
    - '.xmonad'
    - 'wallpaper/current'

- name: Configure .Xresources
  copy:
    src: "Xresources"
    dest: "{{ home_dir }}/.Xresources"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure xmonad
  template:
    src: "xmonad/xmonad.hs.j2"
    dest: "{{ home_dir }}/.xmonad/xmonad.hs"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure title xmobar
  template:
    src: "xmonad/title.xmobarrc.j2"
    dest: "{{ home_dir }}/.xmonad/title.xmobarrc"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure bottom xmobar
  template:
    src: "xmonad/other.xmobarrc.j2"
    dest: "{{ home_dir }}/.xmonad/other.xmobarrc"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure redshift
  template:
    src: "config/redshift.conf.j2"
    dest: "{{ home_dir }}/.config/redshift.conf"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure wallpaper
  copy:
    src: "wallpaper/ansible.jpg"
    dest: "{{ home_dir }}/wallpaper/current/ansible.jpg"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Ensure lightdm conf.d exists
  become: True
  file:
    path: "/etc/lightdm/lightdm.conf.d"
    owner: root
    group: root
    state: directory

- name: "Enable autologin for '{{ x_username }}'"
  become: True
  template:
    src: "12-autologin.conf.j2"
    dest: "/etc/lightdm/lightdm.conf.d/12-autologin.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure X session
  template:
    src: "xsession.j2"
    dest: "{{ home_dir }}/.xsession"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    mode: 0700
