---
- name: Ensure necessary config directories exist
  file:
    path: "{{ home_dir }}/{{ item }}"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    state: directory
  with_items:
    - '.config'
    - '.xmonad'
    - 'wallpaper/current'
    - 'keepassx'

- name: Stat synced password database
  stat:
    path: "{{ home_dir }}/keepassx/passwords.kdbx"
  register: x_keepass_stat

- name: Copy initial keepass database if no existing found
  copy:
    content: "{{ x_keepass_content | b64decode }}"
    dest: "{{ home_dir }}/keepassx/bootstrap.kdbx"
    force: no
  when: not x_keepass_stat.stat.exists

- name: Configure .Xresources
  copy:
    src: "Xresources"
    dest: "{{ home_dir }}/.Xresources"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure xmonad
  template:
    src: "xmonad/xmonad.hs.j2"
    dest: "{{ home_dir }}/.xmonad/xmonad.hs"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure title xmobar
  template:
    src: "xmonad/title.xmobarrc.j2"
    dest: "{{ home_dir }}/.xmonad/title.xmobarrc"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure bottom xmobar
  template:
    src: "xmonad/other.xmobarrc.j2"
    dest: "{{ home_dir }}/.xmonad/other.xmobarrc"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure redshift
  template:
    src: "config/redshift.conf.j2"
    dest: "{{ home_dir }}/.config/redshift.conf"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure the user directories
  template:
    src: "config/user-dirs.dirs.j2"
    dest: "{{ home_dir }}/.config/user-dirs.dirs"

- name: Configure wallpaper
  copy:
    src: "wallpaper/ansible.jpg"
    dest: "{{ home_dir }}/wallpaper/current/ansible.jpg"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"

- name: Configure gpg-agent
  include_tasks: gpg.yml
  when: x_gpg_auth_keygrip != 'changeme'

- name: Ensure lightdm conf.d exists
  become: True
  file:
    path: "/etc/lightdm/lightdm.conf.d"
    owner: root
    group: root
    state: directory

- name: "Disable logging in as guest"
  become: True
  copy:
    src: "10-disable-guest.conf"
    dest: "/etc/lightdm/lightdm.conf.d/10-disable-guest.conf"
    owner: root
    group: root
    mode: 0644

- name: "Enable autologin for '{{ x_username }}'"
  become: True
  template:
    src: "12-autologin.conf.j2"
    dest: "/etc/lightdm/lightdm.conf.d/12-autologin.conf"
    owner: root
    group: root
    mode: 0644

- name: Configure the autolock script
  template:
    src: "scripts/autolock.sh.j2"
    dest: "{{ x_scripts_dir }}/autolock.sh"
    mode: 0755

- name: Configure X session
  template:
    src: "xsession.j2"
    dest: "{{ home_dir }}/.xsession"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    mode: 0700
