---
- name: Add x signing keys
  become: True
  apt_key:
    data: "{{ lookup('file', 'keys/{{ item.keyfile }}') }}"
    state: present
  with_items: "{{ x_repositories + x_extra_repositories }}"

- name: Add apt repositories
  become: True
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
  with_items: "{{ x_repositories + x_extra_repositories }}"

- name: Update package index and install apt packages
  become: True
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ x_packages + x_extra_packages }}"

- name: Install/update the self-written scripts
  copy:
    src: "scripts/"
    dest: "{{ base_scripts_dir }}"
    owner: "{{ x_username }}"
    group: "{{ x_username }}"
    mode: 0755

- name: Copy the RocketChat installer script
  become: True
  copy:
    src: rocketchat.sh
    dest: /root/rocketchat.sh
    owner: root
    group: root
    mode: 0744
  register: rc_install

- name: Install RocketChat
  become: True
  command: /root/rocketchat.sh
  when: rc_install | changed

- name: Configure X setup
  include_tasks: config.yml
  tags:
    - config
